[WIP] Internal Relay Spire Upgrade
chronicleprotocol/relay pull request #11
Opened 2023-06-29 13:45 UTC by teghnet

2023-07-04 16:40 UTC, konstantinzolotarev approved these changes

2023-07-05 11:05 UTC, WesleyCharlesBlake requested changes
Just one q on the version file, nothing major, trivial really

2023-07-05 11:05 UTC, WesleyCharlesBlake commented on version
> +1.16.1-dev.2
shouldnt this change to `1.16.3` ?

2023-07-05 11:09 UTC, teghnet commented on version
> +1.16.1-dev.2
indeed

2023-07-06 15:59 UTC, WesleyCharlesBlake approved these changes

2023-07-06 23:41 UTC, merged